version: '3.8'

services:
  hlr:
    build: .
    ports:
      - "4222:4222"
    environment:
      - HLR_HOST=0.0.0.0
      - HLR_PORT=4222
      - AUTH_SERVICE_URL=http://34.27.10.163:8080
      - AUTH_SERVICE_TIMEOUT=30
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 30s
      timeout: 10s
      retries: 3 