FROM us-central1-docker.pkg.dev/v3-vinoc/epc-core/open5gs-core-dev:latest


# Create necessary directories if they don't exist
RUN mkdir -p /etc/open5gs /etc/freeDiameter /mnt/mme

# Copy configuration files
COPY mme.yaml /etc/open5gs/
COPY mme.conf /etc/freeDiameter/

COPY make_certs.sh /etc/freeDiameter/make_certs.sh
# Set permissions
RUN chmod -R 644 /etc/open5gs/*.yaml \
    && chmod -R 644 /etc/freeDiameter/* \
    && chmod 755 /etc/freeDiameter

# Define environment variables with defaults (will be overridden by k8s)
ENV COMPONENT_NAME=mme

# Use entrypoint script to substitute variables at runtime
COPY mme_init.sh /
RUN chmod +x /mme_init.sh
RUN chmod +x /etc/freeDiameter/make_certs.sh


ENTRYPOINT ["/mme_init.sh"]
CMD ["open5gs-mmed"]
